/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MockTest {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'score' : bigint,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'githubLink' : string,
  'name' : string,
  'techStack' : Array<string>,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'dueDate' : Time,
  'description' : string,
  'priority' : string,
}
export type Time = bigint;
export interface TimelineDay {
  'date' : Time,
  'completed' : boolean,
  'topics' : Array<string>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export interface _SERVICE {
  'addMockTest' : ActorMethod<[string, bigint, Time], MockTest>,
  'addProject' : ActorMethod<[string, string, Array<string>], Project>,
  'addTimelineDay' : ActorMethod<[Time, Array<string>], TimelineDay>,
  'createTask' : ActorMethod<[string, string, Time, string], Task>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllMockTests' : ActorMethod<[], Array<MockTest>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getTimeline' : ActorMethod<[], Array<TimelineDay>>,
  'markTaskComplete' : ActorMethod<[bigint], undefined>,
  'updateTask' : ActorMethod<[bigint, string, string, Time, string], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];