/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'score' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'githubLink' : IDL.Text,
  'name' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const TimelineDay = IDL.Record({
  'date' : Time,
  'completed' : IDL.Bool,
  'topics' : IDL.Vec(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'description' : IDL.Text,
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMockTest' : IDL.Func([IDL.Text, IDL.Nat, Time], [MockTest], []),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Project],
      [],
    ),
  'addTimelineDay' : IDL.Func([Time, IDL.Vec(IDL.Text)], [TimelineDay], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, Time, IDL.Text], [Task], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], []),
  'getTimeline' : IDL.Func([], [IDL.Vec(TimelineDay)], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'githubLink' : IDL.Text,
    'name' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const TimelineDay = IDL.Record({
    'date' : Time,
    'completed' : IDL.Bool,
    'topics' : IDL.Vec(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'description' : IDL.Text,
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    'addMockTest' : IDL.Func([IDL.Text, IDL.Nat, Time], [MockTest], []),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Project],
        [],
      ),
    'addTimelineDay' : IDL.Func([Time, IDL.Vec(IDL.Text)], [TimelineDay], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, Time, IDL.Text], [Task], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], []),
    'getTimeline' : IDL.Func([], [IDL.Vec(TimelineDay)], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };